- name: Run backend API container
  docker_container:
    name: backend-api
    image: lytwz1/backend-api:latest
    pull: true
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/db
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: pwd
    ports:
      - "8080:8080"
    networks:
      - name: network
    state: started
    restart_policy: unless-stopped
  environment:
    DOCKER_HOST: "unix:///var/run/docker.sock"