name: Continuous Integration and Deployment

on:
  push:
    branches: [ main]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push database image
        uses: docker/build-push-action@v4
        with:
          context: ./database
          push: true
          tags: lytwz1/postgres-db:latest
      
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: lytwz1/backend-api:latest
      
      - name: Build and push proxy image
        uses: docker/build-push-action@v4
        with:
          context: ./httpd
          push: true
          tags: lytwz1/httpd-proxy:latest
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H dominique.yang.takima.cloud >> ~/.ssh/known_hosts
          
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
          
      - name: Run Ansible playbook
        run: |
          cd ansible
          ansible-playbook -i inventories/setup.yml deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
