name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: List directories to find correct path
        run: |
          ls -la
          echo "Repository root contents:"
          find . -maxdepth 2 -type d | sort
      
      - name: Build and push database image
        uses: docker/build-push-action@v4
        with:
          context: ./database
          push: true
          tags: lytwz1/postgres-db:latest
