name: Continuous Deployment

on:
  # Se déclenche manuellement depuis l'interface GitHub
  workflow_dispatch:
  
  # Se déclenche lors d'un push sur la branche main
  push:
    branches: [ main ]
    
  # Se déclenche selon un calendrier (pour vérifier les nouvelles images)
  schedule:
    - cron: '0 */4 * * *'  # Toutes les 4 heures

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Ansible and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible docker
        
    - name: Check for DockerHub image updates
      id: check_images
      run: |
        # Vérifier si de nouvelles images sont disponibles
        TRIGGER_DEPLOY="false"
        
        # Obtenir les digests des images (plus fiable que la date)
        DB_DIGEST=$(curl -s "https://hub.docker.com/v2/repositories/lytwz1/postgres-db/tags/latest" | jq -r '.images[0].digest // empty' 2>/dev/null || echo "")
        API_DIGEST=$(curl -s "https://hub.docker.com/v2/repositories/lytwz1/backend-api/tags/latest" | jq -r '.images[0].digest // empty' 2>/dev/null || echo "")
        PROXY_DIGEST=$(curl -s "https://hub.docker.com/v2/repositories/lytwz1/httpd-proxy/tags/latest" | jq -r '.images[0].digest // empty' 2>/dev/null || echo "")
        
        echo "DB image digest: $DB_DIGEST"
        echo "API image digest: $API_DIGEST"
        echo "Proxy image digest: $PROXY_DIGEST"
        
        # Créer un fichier pour les digests actuels
        echo "db:$DB_DIGEST" > current_digests.txt
        echo "api:$API_DIGEST" >> current_digests.txt
        echo "proxy:$PROXY_DIGEST" >> current_digests.txt
        
        # Vérifier si le fichier des digests précédents existe
        if [ -f "previous_digests.txt" ]; then
          # Comparer avec les digests précédents
          if ! diff -q current_digests.txt previous_digests.txt > /dev/null; then
            echo "Modifications d'images détectées!"
            diff previous_digests.txt current_digests.txt || true
            TRIGGER_DEPLOY="true"
          else
            echo "Aucune modification d'image détectée"
          fi
        else
          echo "Premier déploiement - aucun historique disponible"
          TRIGGER_DEPLOY="true"
        fi
        
        # En cas de push ou déclenchement manuel, déployer dans tous les cas
        if [[ "${{ github.event_name }}" == "push" || "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "Workflow déclenché par push ou manuellement"
          TRIGGER_DEPLOY="true"
        fi
        
        # Sauvegarder les digests actuels pour la prochaine exécution
        cp current_digests.txt previous_digests.txt
        
        echo "deploy=$TRIGGER_DEPLOY" >> $GITHUB_OUTPUT
      
    - name: Configure SSH
      if: steps.check_images.outputs.deploy == 'true'
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H dominique.yang.takima.cloud >> ~/.ssh/known_hosts
      
    - name: Test Ansible connection
      if: steps.check_images.outputs.deploy == 'true'
      run: |
        ansible all -i ansible/inventories/setup.yml -m ping
      
    - name: Deploy with Ansible
      if: steps.check_images.outputs.deploy == 'true'
      run: |
        # Forcer le pull des dernières images
        ansible all -i ansible/inventories/setup.yml -m shell -a "docker pull lytwz1/postgres-db:latest" --become
        ansible all -i ansible/inventories/setup.yml -m shell -a "docker pull lytwz1/backend-api:latest" --become
        ansible all -i ansible/inventories/setup.yml -m shell -a "docker pull lytwz1/httpd-proxy:latest" --become
        
        # Déployer l'application
        ansible-playbook -i ansible/inventories/setup.yml ansible/deploy.yml
      
    - name: Verify deployment
      if: steps.check_images.outputs.deploy == 'true'
      run: |
        echo "Waiting for services to start..."
        sleep 30
        
        # Vérifier que les conteneurs sont en cours d'exécution
        ansible all -i ansible/inventories/setup.yml -m shell -a "docker ps" --become
        
        # Tester l'API
        curl -s http://dominique.yang.takima.cloud:8080/actuator/health || echo "API health check failed"
        
        # Tester le proxy
        curl -s http://dominique.yang.takima.cloud || echo "Proxy check failed"
        
        echo "Deployment verification completed"
